#!/usr/bin/ksh
#Auth 	  : MX
#Purpose  : Print every VG and size in EASY format
#Platform : HPUX 11.x
#Version  : 2.0
#Update   : Amended to support PVG. 
#	    Shifted KB -> GB inside the loop as higher values were misbehaving.
#	    Works on Legacy and Persistent device names.



	COUNT=1
	echo "SI VG_Name #Disks VG_Size" | awk '{
			printf "%-3s %-20s %-6s %12s\n", $1, $2, $3,$4 ;
		}'
	printf "--------------------------------------------\n"
	for VGS in $(vgdisplay | awk -F / '/VG Name/{print $3}')
        do
		TSIZE=0
		DISKNUM=0
                for disks in $(
                        vgdisplay -v $VGS | \
                        grep -v 'Alternate Link' | \
                        awk '/PV Name/{ print $3}' | \
                        sort -t / -k 4  | \
                        uniq  )

	        	do 
				DISK=$(echo $disks | awk -F / '{print $3}')
				DEVICE=$(echo $disks | awk -F / '{print $4}')	
				TSIZE=$(expr $TSIZE + $(expr $(diskinfo -b /dev/r${DISK}/${DEVICE}) / 1024 / 1024 ) )
				DISKNUM=$(expr ${DISKNUM} + 1 )

        		done
		echo "$COUNT $VGS  $DISKNUM $TSIZE"
		COUNT=$(expr ${COUNT} + 1 )
		
        done  | awk '{
			printf "%-3s %-20s %-6s %9d GB\n", $1, $2, $3,$4 ;
		}'
